steps:
  # Langkah 1: Compile kode Java menggunakan Maven
  - name: "maven:3.9-eclipse-temurin-17"
    entrypoint: mvn
    args: ["package", "-DskipTests"]

  # Langkah 2: Build Docker image menggunakan Dockerfile.jvm bawaan Quarkus
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "src/main/docker/Dockerfile.jvm"
      - "-t"
      - "gcr.io/$PROJECT_ID/github.com/mahfudz19/psych-api:$COMMIT_SHA"
      - "."

  # Langkah 3: Push image ke Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/github.com/mahfudz19/psych-api:$COMMIT_SHA"

  # Langkah 4: Deploy image terbaru ke Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "psych-api-dev"
      - "--image"
      - "gcr.io/$PROJECT_ID/github.com/mahfudz19/psych-api:$COMMIT_SHA"
      - "--region"
      - "asia-southeast1"

# Tambahkan timeout agar build tidak menggantung jika terjadi error
timeout: "1200s"
