# Aplikasi
quarkus.application.name=psych-api
# HTTP Server
quarkus.http.port=8080
quarkus.http.host=localhost
# OpenAPI / Swagger
quarkus.smallrye-openapi.info-title=Psych API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API untuk sistem psikologi
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.enable=true
quarkus.swagger-ui.path=/q/swagger-ui
# Default log level
quarkus.log.level=INFO
# Package-specific log level
quarkus.log.category."com.psycorp.psychapi.feature.auth".level=DEBUG
quarkus.log.category."com.psycorp.psychapi.feature.auth".min-level=DEBUG
# Security Scheme untuk Bearer Token Authentication
mp.openapi.extensions.smallrye.security.schemes.bearerAuth={"type": "http", "scheme": "bearer", "bearerFormat": "JWT", "description": "JWT Bearer token authentication. Masukkan token tanpa prefix 'Bearer '."}
# Database (MongoDB)
quarkus.mongodb.connection-string=${MONGODB_URI}
quarkus.mongodb.database=${MONGODB_DATABASE}
# CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${CORS_ORIGINS}
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with,x-timezone
quarkus.http.cors.exposed-headers=content-disposition
quarkus.http.cors.access-control-allow-credentials=true
# JWT Config (Custom Mapping)
app.jwt.cookie.name=${JWT_COOKIE_NAME:refresh_token}
app.jwt.cookie.domain=${JWT_COOKIE_DOMAIN:}
app.jwt.cookie.secure=${JWT_COOKIE_SECURE:false}
app.jwt.secret=${JWT_SECRET}
# MONGOCK MIGRATION & SEEDER CONFIGURATION
quarkus.mongock.change-logs-scan-package=id.myproject.infrastructure.database.migration,id.myproject.infrastructure.database.seeder
quarkus.mongock.enabled=true
%dev.quarkus.mongock.migrate-at-start=true
%prod.quarkus.mongock.migrate-at-start=false
# MAILER CONFIGURATION
app.frontend.url=${MAILER_FRONTNEND: http://localhost:5173}
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.username=${SMTP_USERNAME: mfz.masyhur97@gmail.com}
quarkus.mailer.password=${SMTP_PASSWORD: xdtg pwsh gbij elsg}
quarkus.mailer.from=noreply@psycorp.com
quarkus.mailer.mock=false
# Google OAuth2
google.client.id=${GOOGLE_OAUTH_CLIENT_ID}
# Debug komunikasi SMTP
# quarkus.log.category."io.quarkus.mailer".level=DEBUG
# quarkus.mailer.log-payload=true